---
- name: 'Deploy Cloudflared Docker Compose'
  hosts: 'all'
  become: true
  vars:
    cloudflared_dir: '/usr/local/cloudflared'

  tasks:
    - name: 'Ensure cloudflared directory exists'
      file:
        path: '{{ cloudflared_dir }}'
        state: directory
        mode: '0755'

    - name: 'Copy docker-compose.yml to cloudflared directory'
      copy:
        src: '{{ cloudflared_dir }}/docker-compose.yml'
        dest: '{{ cloudflared_dir }}/docker-compose.yml'
        mode: '0644'

    - name: 'Extract hostname segment'
      set_fact:
        hostname_segment: |
          {{ inventory_hostname.split('.')[0] | upper }}

    - name: 'Generate .env file with token'
      copy:
        dest: '{{ cloudflared_dir }}/.env'
        content: |
          TUNNEL_TOKEN={{ lookup('vars', 'CF_TUNNEL_TOKEN_' + hostname_segment) | default('') }}
      when: |
        lookup('vars', 'CF_TUNNEL_TOKEN_' + hostname_segment) is defined

    - name: 'Run Docker Compose'
      shell: 'docker-compose up -d'
      args:
        chdir: '{{ cloudflared_dir }}'
      when: |
        lookup('vars', 'CF_TUNNEL_TOKEN_' + hostname_segment) is defined
