name: 'Deploy Cloudflared'
run-name: '${{ github.event_name }} by ${{ github.actor }} #${{ github.run_number }}.${{ github.run_attempt }}'

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on:
      - 'self-hosted'
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v2'
      - name: 'Apply Terraform'
        working-directory: './terraform'
        run: 'terraform apply -auto-approve'
      - name: 'Public cloudflared Docker Compose'
        run: |
          sudo mkdir -p /usr/local/cloudflared
          sudo chmod 0755 /usr/local/cloudflared
          sudo cp ./docker/docker-compose.yml /usr/local/cloudflared
      - name: 'Run Ansible Playbook'
        run: |
          ansible-playbook deploy-cloudflared.yml -i /usr/local/ansible/inventory/hosts.ini \
            --extra-vars "CF_TUNNEL_TOKEN_DEBIAN=${{ secrets.CF_TUNNEL_TOKEN_DEBIAN }}" \
            --extra-vars "CF_TUNNEL_TOKEN_TANKIAN=${{ secrets.CF_TUNNEL_TOKEN_TANKIAN }}"
